### ISSUE TITLE
Images Files Server

### ISSUE THREAD

**Issue by Morgan-Leon** [xxing1982/EDU_SYZT#14]

**Comment by xxing1982** [comment]
1. Customer provide remote storage server and access PATH
2. Communication between system server and storage server is done by FTP protocol

**Comment by xxing1982** [comment]
FTP: 182.92.238.68   
Port: 14147
User: syzt   
Password: syzt2015
Path for books cover：/pic/bookscover/
Path for user image：  /pic/userImages/
Path for user note:

**Comment by xxing1982** [comment]
@jerrywalker0435 verify if FTP server ready for use
