### ISSUE TITLE
[Morgan] teacher my resource error

### ISSUE THREAD

**Issue by xxing1982** [xxing1982/EDU_SYZT#163]
@Morgan-Leon 
1. 右侧过滤默认选项“无限制“不工作，我选中其他选项，再选”无限制“，无反应
2. 查看书籍相关笔记跳转位置不对，下面tab选项位置不对
3. 添加书籍成功或者失败的原因是英文的，需要改成中文

**Comment by Morgan-Leon** [comment]
1、3 已改
