### ISSUE TITLE
Basic Property for DataModeling

### ISSUE THREAD

**Issue by xxing1982** [xxing1982/EDU_SYZT#20]
Refer to docs/cas_reference

**Comment by EiddleChen** [comment]
1. refer to mysql
@jerrywalker0435  book
@jerrywalker0435  user, student, teacher, parent

**Comment by xxing1982** [comment]
book ready

**Comment by xxing1982** [comment]
please add comments for every fields in DB

**Comment by xxing1982** [comment]
book basic properties provided by customer, refer to docs/requirement/

**Comment by Morgan-Leon** [comment]
@jerrywalker0435 deadline:2015.3.27

**Comment by xxing1982** [comment]
@jerrywalker0435 users API need to be implemented ASAP
