### ISSUE TITLE
reduce navigation between entities. Add aggregate concept. between aggregate use FK to navigate.

### ISSUE THREAD

**Issue by Morgan-Leon** [xxing1982/EDU_SYZT#28]
deadline: 2015.3.26 to make final decision

**Comment by Morgan-Leon** [comment]
deadline: 2015.3.26 to make final decision

**Comment by xxing1982** [comment]
1. Association NOT recommended
2. Aggregation usage on demand basis
3. Use FK to replace Aggregation
