### ISSUE TITLE
Applicaiton of spring-security-oauth

### ISSUE THREAD

**Issue by xxing1982** [xxing1982/EDU_SYZT#3]
1. User Guide to distinguish OpenID and OpenAuth:
http://hueniverse.com/2007/10/04/beginners-guide-to-oauth-part-i-overview/
2. Tutorial: 
https://github.com/spring-projects/spring-security-oauth/blob/master/docs/tutorial.md
3. OpenAuth server lib:
http://oauth.net/2/

**Comment by xxing1982** [comment]
@zdp207 please check how to investigate this FWK to our project

**Comment by jerrywalker0435** [comment]
@zdp207 
Spring RestAPI security Tuorial : http://www.petrikainulainen.net/programming/spring-framework/integration-testing-of-spring-mvc-applications-security/

**Comment by zdp207** [comment]
Spring security & oauth framework has been integrate into our system
