### ISSUE TITLE
[All][Student&Teacher] Frontend development

### ISSUE THREAD

**Issue by xxing1982** [xxing1982/EDU_SYZT#35]
Important (2015.5.3):
[Morgan]    MessageCenter_InBox
[Morgan]    MessageCenter_SendMessage
[Morgan]    Student_GiftCenter
[Morgan]    Student_GiftCenter_RedeemGift
[Morgan]    Student_GiftCenter_RedeemGift_Quantity
[Changhui] Teacher_Home
[Eiddle]      Teacher_MyTask_DispatchTask
[Eiddle]      Teacher_MyTask
[Eiddle]      Teacher_MyAward_DispatchAward
[Eiddle]      Teacher_MyAward
[Morgan]    Teacher_MyRecommandation_AddBook
[Morgan]    Teacher_MyRecommandation_AdvancedSearch
[Morgan]    Teacher_MyRecommandation
[Morgan]    Teacher_MyRecommandation_PopularReading
[Morgan]    Teacher_MyRecommandation_QuickSearch

New to do: @EiddleChen @Morgan-Leon @chyang001 @zdp207 @jerrywalker0435 
[Changhui] Student_ReadingTraining_CompetenceTraining_DoTest
[Changhui] Student_ReadingTraining_CompetenceTraining_DoTest_TestResult
[Changhui] Student_ReadingTraining_CompetenceTraining_History
[Changhui] Student_ReadingTraining_SpeedTraining_NotStarted
[Changhui] Student_ReadingTraining_SpeedTraining_Started
[Eiddle]      Teacher_MyRecommandation_TagBook
[Eiddle]      Teacher_MyResource
[Eiddle]      Teacher_ComparisonClass_BooksStatistics
[Eiddle]      Teacher_ComparisonClass_CoinsStatistics
[Eiddle]      Teacher_ComparisonClass_CompetenceMap
[Eiddle]      Teacher_ComparisonClass_ContentMap
[Eiddle]      Teacher_ComparisonStudent

@Morgan-Leon 
Student_BookShelf
Student_MyBookShelf_AddBook_AdvancedSearch
Student_MyBookShelf_AddBook_FeedbackAfterSearch
Student_MyBookShelf_AddBook_QuickSearch
Student_MyBookShelf_AddBook_PopularReading
Student_MyBookShelf_BookDetails_BookOutline
Student_MyBookShelf_BookDetails_BookOverview
Student_MyBookShelf_BookDetails_RelatedNotes
Student_MyBookShelf_BookDetails_RelatedReviews_ifReviewOmitted

@EiddleChen 
Student_MyBookShelf_TakeNote
Student_MyNotes
Student_PersonalProfile
Student_ReadingMoments
Student_ReadingMoments_HotNotes
Student_Statistics_Ranking
Student_Statistics_Summary
Student_PersonalShow

@chyang001 
Login
Student_Home
Student_MyBookShelf_ReviewBook
Student_MyBookShelf_TestCertification
Student_MyBookShelf_TestCertification_TestResultFail
Student_MyBookShelf_TestCertification_TestResultPass
Student_MyBookShelf_TestSubjective
Student_MyTests_CertificationTests
Student_MyTests_SubjectiveTests
Student_MyTests_SubjectiveTests_MyAnswers
Student_MyTests_SubjectiveTests_OtherAnswers

**Comment by EiddleChen** [comment]
## Custom common ui style sheet
* `/css/custom-ui.css` 
  * Page number control
  * nav tabs (testing not global) 
  * Avatar image border shadow
  * buttom-separator (a gray buttom border as a seprator)

## Custom layout 
* `css\pagebody.css`
  * page-body [title|pagarahp]( common style for every page  )
  * modal-dialog ( the bootstrap pupup window custom style override )
