### ISSUE TITLE
[Morgan][Student][Bug] Redeem records order not correctly

### ISSUE THREAD

**Issue by xxing1982** [xxing1982/EDU_SYZT#82]
@Morgan-Leon

**Comment by Morgan-Leon** [comment]
@jerrywalker0435

**Comment by jerrywalker0435** [comment]
@Morgan-Leon what is that mean?

**Comment by Morgan-Leon** [comment]
http://localhost:9999/api/students/1/exchanges?page=0&size=10&direction='desc'
